name: Deploy a Ferozo (FTP)

# Se ejecuta automáticamente cada vez que se sube (push) un cambio a la rama main
on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Subir archivos por FTP
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código del repo
        uses: actions/checkout@v4

      - name: Subir por FTP a Ferozo
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/README.md
